# Generated by Django 5.0.1 on 2024-01-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisit',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Текущий'), ('Saving', 'Сберегательный'), ('Business', 'Бизнес-счет')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Awaiting payment', 'Ожидает оплаты'), ('Paid', 'Оплачена'), ('Canceled', 'Отменена')], max_length=20)),
                ('requisits', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info_pay.requisit')),
            ],
        ),
    ]
