# Generated by Django 5.0.1 on 2024-01-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_pay', '0002_alter_requisit_account_type_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='requisits',
            new_name='requisit',
        ),
    ]
