# Generated by Django 5.0.1 on 2024-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pay', '0003_rename_requisits_application_requisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Awaiting payment'), ('Paid', 'Оплачена'), ('Canceled', 'Отменена')], max_length=20),
        ),
    ]
