# Generated by Django 4.2.9 on 2024-01-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_pay', '0005_alter_application_status_alter_requisit_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='requisit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_pay.requisit'),
        ),
    ]
