# Generated by Django 4.2.9 on 2024-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_pay', '0008_requisit_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisit',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Дебетовая', 'Дебетовая'), ('Кредитная', 'Кредитная'), ('Предоплаченная', 'Предоплаченная')], max_length=20, null=True),
        ),
    ]
